"""empty message

Revision ID: c2625bec0846
Revises: 
Create Date: 2023-06-19 20:59:04.506297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2625bec0846'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donate_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tree_species', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('region_to_sow', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('get_certified', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('donate_payments_donation_id_fkey', type_='foreignkey')
        batch_op.drop_column('donation_id')

    with op.batch_alter_table('donate_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('donate_wallets', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['wallet_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donate_wallets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('donate_users', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    with op.batch_alter_table('donate_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donation_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('donate_payments_donation_id_fkey', 'donations', ['donation_id'], ['donation_id'])
        batch_op.drop_column('get_certified')
        batch_op.drop_column('description')
        batch_op.drop_column('region_to_sow')
        batch_op.drop_column('tree_species')

    # ### end Alembic commands ###
